name: open_workouts
description: A new Flutter project.
publish_to: 'none'
version: 1.0.4+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.63.0
  google_fonts: ^4.0.4
  motion_tab_bar_v2: ^0.2.6
  dropdown_search: ^5.0.6
  material_design_icons_flutter: ^7.0.7296
  number_selection: ^1.0.0
  cached_network_image: ^3.2.3
  path_provider: ^2.0.15
  provider: ^6.0.5
  permission_handler: ^10.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/data/
